"""Nhãn tiếng Việt cho thông số MÁY CHỦ CHÍNH (ngoài SimCity).

SOURCES: mỗi nguồn = 1 file config trên VM (lua hoặc ini) + bố cục nhóm.
Field 'key': tên hằng Lua top-level, hoặc "SECTION.Key" với file INI.
File INI chỉ hiện field CÓ NHÃN (file chứa hàng trăm dòng text hệ thống);
file Lua hiện thêm extras (hằng chưa gắn nhãn) như tab SimCity.
"""

SOURCES = [
    {
        "id": "cfg_server",
        "title": "Cấu hình gameplay (cfg_server.lua)",
        "path": "/home/jxser/server1/script/global/nobitaxd/config/cfg_server.lua",
        "type": "lua",
        "show_extras": True,
        "extras_title": "🗂️ Khác / sự kiện cổ (chưa gắn nhãn)",
        "groups": [
            {"title": "🌱 Tân thủ & khởi tạo", "fields": [
                {"key": "CFG_HoTroTanThu", "label": "Bật hỗ trợ tân thủ", "widget": "toggle",
                 "desc": "BẬT: nhân vật cấp 1 ĐĂNG NHẬP lần đầu được nhận hỗ trợ — đôn lên 'Cấp khởi tạo' bên dưới (mỗi nhân vật chỉ nhận 1 lần)."},
                {"key": "Level_KhoiTao", "label": "Cấp khởi tạo nhân vật mới", "widget": "number", "unit": "cấp", "min": 1, "max": 200, "step": 1,
                 "desc": "Nhân vật cấp 1 đăng nhập được đôn lên cấp này (cần BẬT hỗ trợ tân thủ). Đang để 1 = không đôn gì cả — muốn tân thủ vào game là cấp 90 thì đặt 90. ĐÂY mới là ô quyết định cấp nhân vật mới, không phải chế độ test."},
                {"key": "CFG_SkillNhapMon", "label": "Kỹ năng tặng khi nhập môn", "widget": "number", "min": 0, "max": 3, "step": 1,
                 "desc": "0 = mặc định; 1 = tặng đến kỹ năng 6x; 2 = kỹ năng 6x full hệ; 3 = kỹ năng 6x tất cả phái."},
                {"key": "nLevelThienTu", "label": "Cấp tối đa đồ Thiên Tử", "widget": "number", "min": 0, "max": 10, "step": 1,
                 "desc": "Mức nâng cấp cao nhất của trang bị Thiên Tử (tối đa 10)."},
            ]},
            {"title": "📜 Nhiệm vụ Dã Tẩu", "fields": [
                {"key": "Level_DaTau", "label": "Cấp được nhận nhiệm vụ Dã Tẩu", "widget": "number", "unit": "cấp", "min": 1, "max": 200, "step": 1,
                 "desc": "Người chơi đạt cấp này mới nhận được nhiệm vụ Dã Tẩu."},
                {"key": "SLNV_DaTau", "label": "Số nhiệm vụ Dã Tẩu mỗi ngày", "widget": "number", "unit": "NV", "min": 0, "max": 500, "step": 5,
                 "desc": "Giới hạn số nhiệm vụ Dã Tẩu 1 người làm được trong 1 ngày."},
            ]},
            {"title": "🏯 Tống Kim", "note": "Khung giờ báo danh chỉnh ở tab 📜 Danh sách dữ liệu → 'Giờ báo danh Tống Kim'.", "fields": [
                {"key": "ThamGiaTongKim", "label": "Mở chiến trường Tống Kim", "widget": "toggle",
                 "desc": "TẮT = không ai báo danh Tống Kim được."},
                {"key": "ThoiGianBaoDanhTK", "label": "Thời gian báo danh", "widget": "number", "unit": "phút", "min": 1, "max": 60, "step": 1,
                 "desc": "Mỗi trận mở cửa báo danh bấy nhiêu phút."},
                {"key": "ThoiGianChienDauTK", "label": "Thời gian chiến đấu", "widget": "number", "unit": "phút", "min": 5, "max": 180, "step": 5,
                 "desc": "Một trận Tống Kim kéo dài bấy nhiêu phút."},
                {"key": "SoLanThamGiaTongKimTrongNgay", "label": "Số trận tối đa mỗi ngày / người", "widget": "number", "min": 0, "max": 100, "step": 1,
                 "desc": "Một người chơi vào được tối đa bấy nhiêu trận Tống Kim mỗi ngày."},
                {"key": "SoDiemToiDaMoiTran", "label": "Điểm tối đa mỗi trận", "widget": "number", "min": 0, "max": 100, "step": 1,
                 "desc": "Trần điểm tích lũy 1 trận."},
                {"key": "GioiHanChenhLechTK", "label": "Giới hạn chênh lệch điểm 2 phe", "widget": "number", "min": 0, "max": 10000000, "step": 10000,
                 "desc": "Chênh lệch điểm tối đa giữa Tống và Kim."},
                {"key": "KiemTraIpChongBoostDiemTongKim", "label": "Chặn cày điểm chung IP", "widget": "toggle",
                 "desc": "BẬT: 2 acc cùng IP đánh nhau không được cộng điểm (chống boost)."},
                {"key": "KhongCoNguoiDanhLenDiemTongKim", "label": "Không người vẫn lên điểm", "widget": "toggle",
                 "desc": "BẬT: điểm trận vẫn tăng dù không có người đánh."},
                {"key": "CGF_Battles_1Player", "label": "Số người tối thiểu để được cộng điểm", "widget": "number", "min": 0, "max": 100, "step": 1,
                 "desc": "Trận có ít hơn số người này thì không cộng điểm."},
                {"key": "CapDoTK1", "label": "Mốc cấp vào trận Tương Dương", "widget": "number", "unit": "cấp", "min": 1, "max": 200, "step": 1,
                 "desc": "Dưới mốc này vào chiến trường cấp thấp (Tương Dương)."},
                {"key": "CapDoTK2", "label": "Mốc cấp vào trận Chu Tiên Trấn", "widget": "number", "unit": "cấp", "min": 1, "max": 200, "step": 1,
                 "desc": "Từ mốc CapDoTK1 đến mốc này vào trận trung cấp; trên nữa vào trận cao cấp."},
            ]},
            {"title": "🔥 Phong Hỏa Liên Thành", "fields": [
                {"key": "HoatDongPHLT", "label": "Mở Phong Hỏa Liên Thành", "widget": "toggle", "desc": "0 = tắt, 1 = mở hoạt động."},
                {"key": "SoLanThamGiaPHLTTrongNgay", "label": "Số lần tham gia mỗi ngày", "widget": "number", "min": 0, "max": 100, "step": 1,
                 "desc": "Giới hạn số lần 1 người vào PHLT trong ngày."},
                {"key": "ThoiGianBaoDanhPHLT", "label": "Thời gian báo danh", "widget": "number", "unit": "phút", "min": 1, "max": 60, "step": 1,
                 "desc": "Cửa báo danh mở bấy nhiêu phút (giờ mở nằm trong bảng ThoiGianOpenPHLT)."},
                {"key": "ThoiGianThuThanhPHLT", "label": "Thời gian thủ thành", "widget": "number", "unit": "phút", "min": 5, "max": 120, "step": 5,
                 "desc": "Một trận thủ thành kéo dài bấy nhiêu phút."},
            ]},
            {"title": "💀 Boss Sát Thủ & Vượt Ải", "fields": [
                {"key": "CFG_BossSatThu", "label": "Mở nhiệm vụ Boss Sát Thủ", "widget": "toggle", "desc": "BẬT/TẮT tính năng Boss Sát Thủ."},
                {"key": "SoLuongBossSatThuTrongNgay", "label": "Số Boss Sát Thủ mỗi ngày", "widget": "number", "min": 0, "max": 100, "step": 1,
                 "desc": "Số nhiệm vụ Boss Sát Thủ nhận được trong 1 ngày."},
                {"key": "CFG_GiaTriVanLuongNhanNVBossST", "label": "Phí vạn lượng nhận nhiệm vụ", "widget": "number", "min": 0, "max": 1000, "step": 1,
                 "desc": "Tiền vạn phải nộp để nhận nhiệm vụ Boss Sát Thủ."},
                {"key": "TuDichChuyen", "label": "Tự dịch chuyển đến boss", "widget": "toggle",
                 "desc": "BẬT: nhận nhiệm vụ xong tự dịch chuyển nhanh tới chỗ boss."},
                {"key": "SoLanVuotAiTrongNgay", "label": "Số lần Vượt Ải mỗi ngày", "widget": "number", "min": 0, "max": 100, "step": 1,
                 "desc": "Giới hạn số lần đi Vượt Ải trong ngày."},
                {"key": "SoNguoiThapNhatThamGiaVuotAi", "label": "Số người tối thiểu vào Vượt Ải", "widget": "number", "min": 1, "max": 8, "step": 1,
                 "desc": "Tổ đội cần ít nhất bấy nhiêu người để vào ải."},
            ]},
            {"title": "🪙 Thưởng xu hoạt động", "fields": [
                {"key": "CFG_Xu_Boss_TieuHK", "label": "Xu giết Boss Tiểu Hoàng Kim", "widget": "number", "min": 0, "max": 1000, "step": 1, "desc": "Số xu thưởng khi hạ boss Tiểu Hoàng Kim."},
                {"key": "CFG_Xu_Boss_DaiHK", "label": "Xu giết Boss Đại Hoàng Kim", "widget": "number", "min": 0, "max": 1000, "step": 1, "desc": "Số xu thưởng khi hạ boss Đại Hoàng Kim."},
                {"key": "CFG_Xu_Boss_ThuyTacDauLinh", "label": "Xu Boss Thủy Tặc Đầu Lĩnh", "widget": "number", "min": 0, "max": 1000, "step": 1, "desc": "Số xu thưởng khi hạ Thủy Tặc Đầu Lĩnh."},
                {"key": "CFG_Xu_Boss_ST9x", "label": "Xu Boss Sát Thủ 9x", "widget": "number", "min": 0, "max": 1000, "step": 1, "desc": "Số xu thưởng khi hạ Boss Sát Thủ cấp 9x."},
            ]},
            {"title": "🧪 Chế độ test (cẩn thận khi mở server thật)", "note": "Test KHÔNG tự cộng gì lúc tạo nhân vật — nó mở thêm menu trong LỆNH BÀI TÂN THỦ (vật phẩm phát sẵn trong hành trang khi đăng nhập). Muốn nhân vật mới tự có cấp cao: chỉnh 'Cấp khởi tạo' ở nhóm Tân thủ.", "fields": [
                {"key": "CFG_ChayThuNghiem", "label": "Bật menu test trong Lệnh Bài Tân Thủ", "widget": "toggle",
                 "desc": "BẬT: bấm Lệnh Bài Tân Thủ có thêm mục 'Nhận hỗ trợ Test nhân vật' (nhận cấp/tiền bên dưới), 'Gọi hoạt động Game nhanh' (mở boss, Tống Kim, Thất Thành...), dịch chuyển nhanh. Server thật nên TẮT."},
                {"key": "nlevel_test", "label": "Cấp nhận từ menu test", "widget": "number", "unit": "cấp", "min": 1, "max": 200, "step": 1,
                 "desc": "Bấm 'Nhận hỗ trợ Test nhân vật' trong Lệnh Bài Tân Thủ sẽ được nâng tới cấp này."},
                {"key": "nKimNguyenBao", "label": "KNB nhận từ menu test", "widget": "number", "min": 0, "max": 1000000000, "step": 100, "desc": "Kim Nguyên Bảo phát khi bấm nhận hỗ trợ test."},
                {"key": "nTienDong", "label": "Tiền đồng nhận từ menu test", "widget": "number", "min": 0, "max": 1000000000, "step": 100, "desc": "Tiền đồng phát khi bấm nhận hỗ trợ test."},
                {"key": "nNganLuong", "label": "Ngân lượng nhận từ menu test", "widget": "number", "min": 0, "max": 1000000000, "step": 100000, "desc": "Ngân lượng phát khi bấm nhận hỗ trợ test."},
            ]},
            {"title": "🎛️ Bật / tắt tính năng máy chủ", "note": "Mỗi công tắc = 1 tính năng lớn. Đổi xong phải restart.", "fields": [
                {"key": "CFG_ThienTu", "label": "Trang bị Thiên Tử", "widget": "toggle", "desc": "Hệ thống nâng cấp đồ Thiên Tử."},
                {"key": "CFG_ThatThanhDaiChien", "label": "Thất Thành Đại Chiến", "widget": "toggle", "desc": "Hoạt động công thành 7 thành."},
                {"key": "SoTienBaoDanhCanNop", "label": "— Phí báo danh TTDC (vạn)", "widget": "number", "min": 0, "max": 10000, "step": 1, "desc": "Tiền vạn nộp khi báo danh Thất Thành Đại Chiến."},
                {"key": "SoKhieuChienLenhCanNop", "label": "— Khiêu Chiến Lệnh cần nộp", "widget": "number", "min": 0, "max": 100, "step": 1, "desc": "Số Khiêu Chiến Lệnh nộp khi báo danh."},
                {"key": "CFG_NhiemVuLongNgu", "label": "Nhiệm vụ Long Ngư", "widget": "toggle", "desc": ""},
                {"key": "CFG_LienDau", "label": "Võ Lâm Liên Đấu", "widget": "toggle", "desc": ""},
                {"key": "NPCVoLamLienDau", "label": "— NPC Liên Đấu", "widget": "toggle", "desc": "Hiện NPC báo danh Liên Đấu."},
                {"key": "ShopLienDau", "label": "— Shop Liên Đấu", "widget": "toggle", "desc": ""},
                {"key": "CFG_AnBangHoanMy", "label": "Ấn Bang Hoàn Mỹ", "widget": "toggle", "desc": ""},
                {"key": "CFG_TrangBiBachKim", "label": "Trang bị Bạch Kim", "widget": "toggle", "desc": ""},
                {"key": "CFG_TrungLuyenTrangBiBachKim", "label": "Trùng luyện đồ Bạch Kim", "widget": "toggle", "desc": ""},
                {"key": "CFG_TrangBiHoangKim", "label": "Trang bị Hoàng Kim", "widget": "toggle", "desc": ""},
                {"key": "CFG_DoPhoHoangKim", "label": "Đồ phổ Hoàng Kim", "widget": "toggle", "desc": ""},
                {"key": "CFG_TrangBiHuyenTinh", "label": "Trang bị Huyền Tinh", "widget": "toggle", "desc": ""},
                {"key": "CFG_KhamNamDoXanh", "label": "Khảm nạm đồ xanh", "widget": "toggle", "desc": ""},
                {"key": "CFG_CuaHangTinhLuc", "label": "Cửa hàng Tinh Lực", "widget": "toggle", "desc": ""},
                {"key": "CFG_PhongVanBaoDien", "label": "Phong Vân Bảo Điển", "widget": "toggle", "desc": ""},
                {"key": "CFG_GreatNight", "label": "Sự kiện Great Night", "widget": "toggle", "desc": ""},
                {"key": "CFG_TrungSinh", "label": "Trùng Sinh", "widget": "toggle", "desc": "Hệ thống trùng sinh nhân vật."},
                {"key": "CFG_KyNangTrungSinh4", "label": "— Kỹ năng Trùng Sinh 4", "widget": "toggle", "desc": ""},
                {"key": "CFG_LuyenDanTruyenCong", "label": "Luyện Đan / Truyền Công", "widget": "toggle", "desc": ""},
                {"key": "CFG_ThuanMaThuat", "label": "Thuần Mã Thuật", "widget": "toggle", "desc": ""},
                {"key": "CFG_ViemDe", "label": "Viêm Đế", "widget": "toggle", "desc": "Hệ thống vũ khí Viêm Đế."},
                {"key": "CFG_TopTuanTongKim", "label": "Top tuần Tống Kim", "widget": "toggle", "desc": "Bảng xếp hạng Tống Kim theo tuần."},
                {"key": "CFG_DoiTrangBiXanhDiemTK", "label": "Đổi đồ xanh bằng điểm Tống Kim", "widget": "toggle", "desc": ""},
                {"key": "CFG_TinSu", "label": "Tín Sứ", "widget": "toggle", "desc": ""},
                {"key": "CFG_OnlineNhanThuong", "label": "Online nhận thưởng", "widget": "toggle", "desc": "Treo máy đủ giờ nhận quà."},
                {"key": "CFG_OnlineNhanThuong_ActiveGetHuyenTinh", "label": "— Online nhận Huyền Tinh", "widget": "toggle", "desc": ""},
                {"key": "ScriptShopLienDau", "label": "— Shop Liên Đấu (bản script)", "widget": "toggle", "desc": "Phiên bản shop Liên Đấu chạy bằng script."},
            ]},
            {"title": "📅 Thông tin mở server", "fields": [
                {"key": "ThoiGianHetHanDiemTP", "label": "Hạn chót tính điểm TP", "widget": "text",
                 "desc": "Thời điểm hết hạn điểm TP, viết liền dạng NămThángNgàyGiờPhút (vd 202204161000 = 10:00 16/04/2022)."},
                {"key": "ThoiGianOpenStr", "label": "Dòng chữ giờ mở server", "widget": "text",
                 "desc": "Chuỗi hiển thị cho người chơi (chữ Việt trong file là mã TCVN3 — sửa ở tab Sửa file thô với 'Hiện tiếng Việt' cho chuẩn)."},
            ]},
            {"title": "💰 Shop thu phí & donate", "note": "Giá bán trong shop duy trì máy chủ. Tên viết tắt theo item trong shop.", "fields": [
                {"key": "CFG_ShopItemThuPhi", "label": "Mở shop item thu phí", "widget": "toggle", "desc": "BẬT/TẮT shop item phí duy trì máy chủ."},
                {"key": "nKNB_NhatKy", "label": "Giá KNB: Nhật Ký", "widget": "number", "min": 0, "max": 100000, "step": 1, "desc": "Giá Kim Nguyên Bảo của món Nhật Ký."},
                {"key": "nTD_THP", "label": "Giá tiền đồng: THP", "widget": "number", "min": 0, "max": 100000, "step": 1, "desc": "Giá món viết tắt THP trong shop phí."},
                {"key": "nTD_TDP", "label": "Giá tiền đồng: TDP", "widget": "number", "min": 0, "max": 100000, "step": 1, "desc": "Giá món viết tắt TDP trong shop phí."},
                {"key": "nTD_TTTAP", "label": "Giá tiền đồng: TTTAP", "widget": "number", "min": 0, "max": 100000, "step": 1, "desc": "Giá món viết tắt TTTAP trong shop phí."},
                {"key": "nTD_DTLB", "label": "Giá tiền đồng: DTLB", "widget": "number", "min": 0, "max": 100000, "step": 1, "desc": "Giá món viết tắt DTLB trong shop phí."},
                {"key": "nTD_LBTT", "label": "Giá tiền đồng: LBTT", "widget": "number", "min": 0, "max": 100000, "step": 1, "desc": "Giá món viết tắt LBTT trong shop phí."},
                {"key": "ID_Skill_Donate", "label": "[nội bộ] ID skill tặng khi donate", "widget": "number", "min": 0, "max": 10000, "step": 1,
                 "desc": "Mã kỹ năng tặng người donate. KHÔNG đổi trừ khi biết chính xác ID skill mới."},
            ]},
            {"title": "🧧 Thưởng & hỗ trợ khác", "fields": [
                {"key": "CGF_SL_CamNangHK", "label": "Số Cẩm Nang HK mỗi ngày", "widget": "number", "min": 0, "max": 10000, "step": 10,
                 "desc": "Số lượng Cẩm Nang một người dùng được trong 1 ngày."},
                {"key": "CFG_BaoRuongThanBiBacDauLaoNhan", "label": "Rương Thần Bí (Bắc Đẩu Lão Nhân)", "widget": "toggle", "desc": "Tính năng báo rương Thần Bí ở NPC Bắc Đẩu Lão Nhân."},
                {"key": "CFG_NhiemVuGiaiHuynhDeBacDauLaoNhan", "label": "NV Giải Huynh Đệ (Bắc Đẩu Lão Nhân)", "widget": "toggle", "desc": ""},
                {"key": "CFG_ThuongToanServerBossDocCoThienPhong", "label": "Thưởng toàn server boss Độc Cô Thiên Phong", "widget": "toggle", "desc": "Cả server nhận thưởng khi boss Độc Cô Thiên Phong bị hạ."},
                {"key": "CFG_newbielvlup", "label": "Thưởng thăng cấp tân thủ", "widget": "toggle", "desc": ""},
                {"key": "CFG_playerlvlup", "label": "Thưởng thăng cấp người chơi", "widget": "toggle", "desc": ""},
                {"key": "CFG_feiyunrenwu", "label": "Thưởng mốc cấp 60/90/100", "widget": "toggle", "desc": "Nhận thưởng khi đạt các mốc cấp 60, 90, 100."},
                {"key": "CFG_takeboxaward", "label": "Nhận thưởng rương (takeboxaward)", "widget": "toggle", "desc": ""},
                {"key": "CFG_jx_web", "label": "Tính năng web JX", "widget": "toggle", "desc": "Kết nối tính năng web của bản gốc — thường để TẮT."},
                {"key": "CFG_tagnewplayer", "label": "Gắn nhãn người chơi mới", "widget": "toggle", "desc": ""},
                {"key": "CFG_ChangeDestiny", "label": "Đổi vận mệnh (ChangeDestiny)", "widget": "toggle", "desc": ""},
                {"key": "CFG_fenghuo_hero", "label": "Anh hùng Phong Hỏa", "widget": "toggle", "desc": ""},
                {"key": "CFG_revival", "label": "Tính năng hồi sinh (revival)", "widget": "toggle", "desc": ""},
            ]},
            {"title": "🎪 Sự kiện cổ (2005–2010)", "note": "Bật cờ CHỈ làm vật phẩm/script event hoạt động — CHƯA có nguồn ra đồ event (hiện không quái nào rơi, không NPC event nào được đặt trong npcs.txt). Muốn event chạy thật phải thêm nguồn ra: đổi bảng rơi đồ của quái sang bảng event, thêm NPC event, hoặc GM phát đồ. Client ĐÃ có sẵn tài nguyên (settings/event + hình trong pak) — KHÔNG cần sửa client.", "fields": [
                {"key": "CFG_vm_birthplan", "label": "SN VLTK 1 tuổi (2006)", "widget": "toggle", "desc": ""},
                {"key": "CFG_Act2Years2007", "label": "SN VLTK 2 tuổi (2007)", "widget": "toggle", "desc": ""},
                {"key": "CFG_pingzi", "label": "SN VLTK 3 tuổi (2008)", "widget": "toggle", "desc": ""},
                {"key": "CFG_jxanniversary3", "label": "SN VLTK 3 (bản anniversary)", "widget": "toggle", "desc": ""},
                {"key": "CFG_birthday_jieri_2009", "label": "SN VLTK 2009 (Hùng Bá Thiên Hạ)", "widget": "toggle", "desc": ""},
                {"key": "CFG_yn_chunjie", "label": "Tết Nguyên Đán 2005", "widget": "toggle", "desc": "Có mâm ngũ quả."},
                {"key": "CFG_ma_chunjie", "label": "Tết Nguyên Đán 2006", "widget": "toggle", "desc": ""},
                {"key": "CFG_newyear_2007", "label": "Tết Nguyên Đán 2007", "widget": "toggle", "desc": ""},
                {"key": "CFG_newyear_2008", "label": "Tết Nguyên Đán 2008", "widget": "toggle", "desc": ""},
                {"key": "CFG_newyear_2009", "label": "Tết Nguyên Đán 2009", "widget": "toggle", "desc": ""},
                {"key": "CFG_springfestival07", "label": "Lễ hội xuân 2007", "widget": "toggle", "desc": ""},
                {"key": "CFG_spring_2006", "label": "Lễ hội xuân 2006", "widget": "toggle", "desc": ""},
                {"key": "CFG_mid_autumn05", "label": "Trung Thu 2005", "widget": "toggle", "desc": ""},
                {"key": "CFG_mid_autumn06", "label": "Trung Thu 2006", "widget": "toggle", "desc": ""},
                {"key": "CFG_zhongqiu2007", "label": "Trung Thu 2007", "widget": "toggle", "desc": ""},
                {"key": "CFG_zhongqiu_jieri_2008", "label": "Trung Thu 2008", "widget": "toggle", "desc": ""},
                {"key": "CFG_zhongqiu_jieri_2009", "label": "Trung Thu 2009", "widget": "toggle", "desc": ""},
                {"key": "CFG_xmas2006", "label": "Giáng Sinh 2006", "widget": "toggle", "desc": ""},
                {"key": "CFG_xmas2007", "label": "Giáng Sinh 2007", "widget": "toggle", "desc": ""},
                {"key": "CFG_shengdan_jieri2008", "label": "Giáng Sinh 2008", "widget": "toggle", "desc": ""},
                {"key": "CFG_qingren_jieri_2009", "label": "Lễ Tình Nhân 2009", "widget": "toggle", "desc": ""},
                {"key": "CFG_funv_jieri_2008", "label": "Quốc tế Phụ nữ 2008", "widget": "toggle", "desc": ""},
                {"key": "CFG_funv_jieri_2009", "label": "Quốc tế Phụ nữ 2009", "widget": "toggle", "desc": ""},
                {"key": "CFG_cookies2007", "label": "Giỗ tổ 10/3 (2007)", "widget": "toggle", "desc": ""},
                {"key": "CFG_menglan_2006", "label": "Vu Lan 2006", "widget": "toggle", "desc": ""},
                {"key": "CFG_2006vm_NationalDay", "label": "Quốc Khánh 2006 (bản VN)", "widget": "toggle", "desc": ""},
                {"key": "CFG_nationalday_2006", "label": "Quốc Khánh 10/2006", "widget": "toggle", "desc": ""},
                {"key": "CFG_GUOQING2007", "label": "Quốc Khánh 2007", "widget": "toggle", "desc": ""},
                {"key": "CFG_guoqing_jieri_2008", "label": "Quốc Khánh 2008", "widget": "toggle", "desc": ""},
                {"key": "CFG_guoqing_jieri_2009", "label": "Quốc Khánh 2009", "widget": "toggle", "desc": ""},
                {"key": "CFG_jiefang_jieri2008", "label": "Giải phóng 30/4 (2008)", "widget": "toggle", "desc": ""},
                {"key": "CFG_jiefang_jieri2009", "label": "Giải phóng 30/4 (2009)", "widget": "toggle", "desc": ""},
                {"key": "CFG_jiefang_jieri2010", "label": "Giải phóng 30/4 (2010)", "widget": "toggle", "desc": ""},
                {"key": "CFG_nanfangjiefangri", "label": "Giải phóng miền Nam", "widget": "toggle", "desc": ""},
                {"key": "CFG_teachersday06", "label": "Nhà giáo 2006", "widget": "toggle", "desc": ""},
                {"key": "CFG_teacher_day_200711", "label": "Nhà giáo 11/2007", "widget": "toggle", "desc": ""},
                {"key": "CFG_jiaoshi0810", "label": "Nhà giáo 2008", "widget": "toggle", "desc": ""},
                {"key": "CFG_jiaoshi0910", "label": "Nhà giáo 2009", "widget": "toggle", "desc": ""},
                {"key": "CFG_mengjiang2007", "label": "Mãnh Tướng 2007", "widget": "toggle", "desc": ""},
                {"key": "CFG_superplayeract2007", "label": "Cao thủ 2007", "widget": "toggle", "desc": ""},
                {"key": "CFG_poster", "label": "Sự kiện Poster", "widget": "toggle", "desc": ""},
                {"key": "CFG_storm", "label": "Sự kiện Storm", "widget": "toggle", "desc": ""},
            ]},
        ],
    },
    {
        "id": "gamesetting",
        "title": "Tỉ lệ máy chủ (gamesetting.ini)",
        "path": "/home/jxser/server1/settings/gamesetting.ini",
        "type": "ini",
        "show_extras": False,
        "groups": [
            {"title": "⭐ Tỉ lệ kinh nghiệm & tiền", "note": "100 = x1 (gốc), 200 = x2, 500 = x5... Đổi xong restart server.", "fields": [
                {"key": "ServerConfig.ExpRate", "label": "Tỉ lệ kinh nghiệm (Exp)", "widget": "number", "unit": "%", "min": 1, "max": 100000, "step": 50,
                 "desc": "Nhân kinh nghiệm toàn server: 100 = bình thường, 200 = x2 exp, 1000 = x10."},
                {"key": "ServerConfig.MoneyRate", "label": "Tỉ lệ tiền rơi", "widget": "number", "unit": "%", "min": 1, "max": 100000, "step": 50,
                 "desc": "Nhân số tiền quái rơi ra: 100 = bình thường, 200 = gấp đôi."},
            ]},
            {"title": "💎 Khảm nạm bảo thạch", "note": "Tỉ lệ % thành công khi ghép 2 viên đá cấp N thành 1 viên cấp N+1. Cấp càng cao càng khó.", "fields": [
                {"key": f"ENCHASER.LevelUpRate{i}", "label": f"Ghép đá lên cấp {i} — tỉ lệ thành công", "widget": "number", "unit": "%", "min": 0, "max": 100, "step": 5,
                 "desc": f"Xác suất ghép thành công đá cấp {i}. 100 = luôn thành công, 0 = không bao giờ."} for i in range(1, 10)
            ]},
            {"title": "🏆 Danh vọng", "fields": [
                {"key": "Repute.MaxRepute", "label": "Danh vọng tối đa", "widget": "number", "min": 0, "max": 1000000, "step": 1000,
                 "desc": "Điểm danh vọng cao nhất một người chơi tích được. Mặc định 32.000."},
                {"key": "Repute.MinRepute", "label": "Danh vọng tối thiểu", "widget": "number", "min": -100000, "max": 100000, "step": 100,
                 "desc": "Sàn danh vọng (bị trừ tối đa tới mức này). Mặc định 0."},
            ]},
            {"title": "🛡️ Giới hạn & sát thương", "fields": [
                {"key": "ServerConfig.MaxPlayerCount", "label": "Số người chơi tối đa (engine)", "widget": "number", "unit": "người", "min": 1, "max": 10000, "step": 50,
                 "desc": "Trần người chơi của engine game (tách biệt với MaxPlayer ở servercfg.ini — nên chỉnh cả hai cùng mức)."},
                {"key": "ServerConfig.NpcPoisonDamageMax", "label": "Sát thương độc tối đa lên quái", "widget": "number", "min": 0, "max": 100000000, "step": 10000,
                 "desc": "Trần sát thương mỗi nhịp của hiệu ứng độc đánh lên NPC/quái."},
                {"key": "ServerConfig.PlayerPoisonDamageMax", "label": "Sát thương độc tối đa lên người", "widget": "number", "min": 0, "max": 100000000, "step": 10000,
                 "desc": "Trần sát thương mỗi nhịp của hiệu ứng độc đánh lên người chơi."},
            ]},
            {"title": "🎲 Trò xúc xắc", "note": "Tiền thưởng khi lắc xúc xắc ra đôi / bộ ba / dãy liên tiếp, theo mặt 1→6.", "fields": [
                {"key": "DiceGame.MaxBet", "label": "Tiền cược tối đa mỗi ván", "widget": "number", "unit": "lượng", "min": 0, "max": 100000000, "step": 1000,
                 "desc": "Người chơi đặt cược tối đa bấy nhiêu một ván."},
                *[{"key": f"DiceGame.TwiceBonus{i}", "label": f"Thưởng ra ĐÔI mặt {i}", "widget": "number", "unit": "lượng", "min": 0, "max": 100000000, "step": 100,
                   "desc": f"Tiền thưởng khi ra 2 con {i} giống nhau."} for i in range(1, 7)],
                *[{"key": f"DiceGame.ThriceBonus{i}", "label": f"Thưởng ra BỘ BA mặt {i}", "widget": "number", "unit": "lượng", "min": 0, "max": 100000000, "step": 100,
                   "desc": f"Tiền thưởng khi ra 3 con {i} giống nhau."} for i in range(1, 7)],
                *[{"key": f"DiceGame.SeriesBonus{i}", "label": f"Thưởng ra DÃY liên tiếp #{i}", "widget": "number", "unit": "lượng", "min": 0, "max": 100000000, "step": 100,
                   "desc": "Tiền thưởng khi các mặt tạo thành dãy số liên tiếp."} for i in range(1, 5)],
            ]},
        ],
    },
    {
        "id": "auction",
        "title": "Đấu giá (auction.ini)",
        "path": "/home/jxser/server1/settings/auction.ini",
        "type": "ini",
        "show_extras": False,
        "groups": [
            {"title": "🔨 Đấu giá", "fields": [
                {"key": "Main.MinBasePrice", "label": "Giá khởi điểm tối thiểu", "widget": "number", "unit": "lượng", "min": 0, "max": 1000000000, "step": 100000,
                 "desc": "Đăng món đấu giá phải đặt giá khởi điểm từ mức này trở lên. Mặc định 1.000.000."},
                {"key": "Main.AddPricePerTime", "label": "Bước giá mỗi lần trả", "widget": "number", "unit": "lượng", "min": 0, "max": 100000000, "step": 1000,
                 "desc": "Mỗi lần trả giá phải cao hơn giá trước ít nhất bấy nhiêu."},
                {"key": "Main.TaxRate", "label": "Thuế đấu giá", "widget": "number", "unit": "%", "min": 0, "max": 100, "step": 1,
                 "desc": "Phần trăm trừ vào tiền người bán nhận được. Mặc định 12%."},
                {"key": "Main.FeePerRound", "label": "Phí mỗi vòng đấu giá", "widget": "number", "unit": "lượng", "min": 0, "max": 100000000, "step": 1000,
                 "desc": "Lệ phí đăng món mỗi vòng."},
                {"key": "Main.MaxAuctionPerPlayer", "label": "Số món tối đa mỗi người", "widget": "number", "min": 0, "max": 100, "step": 1,
                 "desc": "Một người được đăng bán tối đa bấy nhiêu món cùng lúc."},
                {"key": "Main.MaxAuctionPerCity", "label": "Số món tối đa mỗi thành", "widget": "number", "min": 0, "max": 1000, "step": 1,
                 "desc": "Sàn đấu giá mỗi thành chứa tối đa bấy nhiêu món."},
            ]},
        ],
    },
    {
        "id": "killer",
        "title": "Truy nã (killer.ini)",
        "path": "/home/jxser/server1/settings/killer.ini",
        "type": "ini",
        "show_extras": False,
        "groups": [
            {"title": "🗡️ Truy nã", "fields": [
                {"key": "Main.MoneyPerHour", "label": "Tiền treo thưởng mỗi giờ", "widget": "number", "unit": "lượng", "min": 0, "max": 100000000, "step": 1000,
                 "desc": "Mỗi giờ nhiệm vụ truy nã còn hiệu lực, tiền thưởng cộng thêm bấy nhiêu."},
                {"key": "Main.MinTargetLevel", "label": "Cấp tối thiểu bị truy nã", "widget": "number", "unit": "cấp", "min": 1, "max": 200, "step": 5,
                 "desc": "Chỉ truy nã được người chơi từ cấp này trở lên. LƯU Ý: câu thông báo 'dưới cấp 50...' trong game là chữ viết cứng — đổi số xong nên sửa câu đó ở tab Sửa file thô cho khớp."},
                {"key": "Main.MinReward", "label": "Tiền thưởng tối thiểu", "widget": "number", "unit": "lượng", "min": 0, "max": 1000000000, "step": 10000,
                 "desc": "Treo thưởng truy nã phải đặt từ mức này trở lên."},
            ]},
        ],
    },
    {
        "id": "limittime",
        "title": "Giới hạn giờ chơi (player_limittime.ini)",
        "path": "/home/jxser/server1/settings/player_limittime.ini",
        "type": "ini",
        "show_extras": False,
        "groups": [
            {"title": "😴 Giới hạn giờ chơi (chống nghiện)", "note": "Đơn vị GIÂY: 3600 = 1 giờ, 28800 = 8 giờ. Đã kiểm chứng: engine đọc file này (không phải tiredwarning.ini).", "fields": [
                {"key": "LimitTime.OnlineTiredTime", "label": "Online bao lâu thì 'mệt mỏi'", "widget": "number", "unit": "giây", "min": 0, "max": 864000, "step": 1800,
                 "desc": "Chơi liên tục quá mức này bị giảm exp/drop theo cơ chế mệt mỏi. Mặc định 28.800 (8 giờ)."},
                {"key": "LimitTime.OnlineIllHealthTime", "label": "Online bao lâu thì 'suy nhược'", "widget": "number", "unit": "giây", "min": 0, "max": 864000, "step": 1800,
                 "desc": "Mức nặng hơn mệt mỏi. Mặc định 36.000 (10 giờ)."},
                {"key": "LimitTime.OfflineResumeTime", "label": "Offline bao lâu thì hồi phục", "widget": "number", "unit": "giây", "min": 0, "max": 864000, "step": 1800,
                 "desc": "Thoát game đủ lâu sẽ hết mệt mỏi. Mặc định 36.000 (10 giờ)."},
                {"key": "Config.TireKickPlayer", "label": "Đá người chơi khi quá mệt", "widget": "toggle",
                 "desc": "BẬT: chơi quá lâu bị đá khỏi game. TẮT: chỉ giảm hiệu quả cày."},
                {"key": "Config.bForbitStallWhenTire", "label": "Cấm bày bán khi mệt", "widget": "toggle",
                 "desc": "BẬT: đang mệt mỏi thì không mở sạp được."},
                {"key": "Config.bForbitTradeWhenTire", "label": "Cấm giao dịch khi mệt", "widget": "toggle",
                 "desc": "BẬT: đang mệt mỏi thì không giao dịch được."},
            ]},
        ],
    },
    {
        "id": "activity_bonus",
        "title": "Khung giờ thưởng (cfg_activity_bonus.lua)",
        "path": "/home/jxser/server1/script/global/nobitaxd/config/cfg_activity_bonus.lua",
        "type": "lua",
        "show_extras": False,
        "groups": [
            {"title": "🎁 Khung giờ hoạt động thưởng", "note": "Khung giờ vàng các hoạt động thưởng theo thứ trong tuần (Boss Sát Thủ...).", "fields": [
                {"key": "nHour_star", "label": "Giờ bắt đầu khung thưởng", "widget": "number", "min": 0, "max": 2359, "step": 100,
                 "desc": "Viết dạng GiờPhút: 2000 = 20:00 tối. Mặc định 2000."},
                {"key": "nHour_end", "label": "Giờ kết thúc khung thưởng", "widget": "number", "min": 0, "max": 2359, "step": 100,
                 "desc": "Viết dạng GiờPhút: 2100 = 21:00. Phải sau giờ bắt đầu."},
                {"key": "nLevel", "label": "Cấp tối thiểu nhận thưởng Chủ Nhật", "widget": "number", "unit": "cấp", "min": 1, "max": 200, "step": 5,
                 "desc": "Dưới cấp này không nhận được thưởng hoạt động Chủ Nhật. Mặc định 90."},
            ]},
        ],
    },
    {
        "id": "misc_mod",
        "title": "Dã Tẩu Lệnh (dataulenhbai.lua)",
        "path": "/home/jxser/server1/script/global/nobitaxd/item/dataulenhbai.lua",
        "type": "lua",
        "show_extras": False,
        "groups": [
            {"title": "🎫 Dã Tẩu Lệnh", "fields": [
                {"key": "DTL_LIMIT", "label": "Số Dã Tẩu Lệnh dùng mỗi ngày", "widget": "number", "unit": "cái", "min": 0, "max": 1000, "step": 5,
                 "desc": "Một người dùng tối đa bấy nhiêu Dã Tẩu Lệnh trong 1 ngày. Mặc định 30."},
            ]},
        ],
    },
    {
        "id": "thuongtop",
        "title": "Thưởng đua top (thuongtop.lua)",
        "path": "/home/jxser/server1/script/global/nobitaxd/npc/thuongtop.lua",
        "type": "lua",
        "show_extras": False,
        "groups": [
            {"title": "🏅 Thưởng đua top", "fields": [
                {"key": "CapDo", "label": "Cấp tối thiểu nhận thưởng top", "widget": "number", "unit": "cấp", "min": 1, "max": 200, "step": 5,
                 "desc": "Dưới cấp này NPC báo 'Cấp độ ngươi quá thấp'. Mặc định 120."},
            ]},
        ],
    },
    {
        "id": "hoanbinh",
        "title": "Hoán Bính Vũ Khí (hoanbinhvukhi/head.lua)",
        "path": "/home/jxser/server1/script/global/nobitaxd/vdk/tinhnang/hoanbinhvukhi/head.lua",
        "type": "lua",
        "show_extras": False,
        "groups": [
            {"title": "⚔️ Hoán Bính Vũ Khí", "fields": [
                {"key": "nPractice_Fees", "label": "Phí hoán bính vũ khí", "widget": "number", "unit": "lượng", "min": 0, "max": 1000000000, "step": 50000,
                 "desc": "Tiền phải trả mỗi lần đổi kiểu vũ khí. Mặc định 500.000."},
            ]},
        ],
    },
    {
        "id": "taxrates",
        "title": "Thuế bày bán (taxrates.ini)",
        "path": "/home/jxser/server1/settings/taxrates.ini",
        "type": "ini",
        "show_extras": False,
        "groups": [
            {"title": "🏪 Thuế bày bán trong thành", "fields": [
                {"key": "Main.CommonRate", "label": "Thuế bày bán chung", "widget": "number", "unit": "%", "min": 0, "max": 100, "step": 1,
                 "desc": "Thuế trừ vào tiền bán hàng bày bán, áp cho thành không có mức riêng. LƯU Ý: đặt 0 dễ bị lợi dụng rửa tiền lỗi game."},
                {"key": "Main.MinPlayerLevelAllowed", "label": "Cấp tối thiểu được bày bán", "widget": "number", "unit": "cấp", "min": 1, "max": 200, "step": 1,
                 "desc": "Người chơi dưới cấp này không mở sạp bày bán được."},
            ]},
        ],
    },
    {
        "id": "servercfg",
        "title": "Hệ thống (servercfg.ini)",
        "path": "/home/jxser/server1/servercfg.ini",
        "type": "ini",
        "show_extras": False,
        "groups": [
            {"title": "🖥️ Giới hạn máy chủ", "note": "File này còn chứa IP/port hệ thống — KHÔNG đưa lên web để tránh sập server.", "fields": [
                {"key": "Overload.MaxPlayer", "label": "Số người chơi tối đa", "widget": "number", "unit": "người", "min": 1, "max": 5000, "step": 50,
                 "desc": "Server từ chối đăng nhập khi vượt số này. VM hiện 4 CPU / 8GB RAM — đặt quá cao game sẽ lag."},
            ]},
        ],
    },
]

# LOOKUP key -> field meta (mọi nguồn)
LOOKUP = {}
for _s in SOURCES:
    for _g in _s["groups"]:
        for _f in _g["fields"]:
            LOOKUP[_f["key"]] = _f
