"""Nhãn tiếng Việt + ghi chú cho MỌI thông số SimCity.

- GROUPS: bố cục hiển thị cho config.lua (mỗi field trỏ tới 'key' khi parse:
  tên hằng, hoặc "TABLE.field" nếu nằm trong table).
- LOOKUP: tra nhanh key/tên -> metadata (dùng cho cả hằng số ở file khác).

widget: "number" | "toggle" | "text"
Field có 'file' = nằm ở file khác (đường dẫn tương đối trong thư mục simcity).
"""

# ---- config.lua : bố cục nhóm ----
GROUPS = [
    {"title": "🧍 Số lượng nhân sĩ (bot)", "note": "Bot trong map gồm 2 loại: bot ĐI LẠI (chỉnh ở 2 ô đầu) và bot đứng BÁN HÀNG (chỉnh ở các ô ít nhất/nhiều nhất).", "fields": [
        {"key": "THANHTHI_SIZE", "label": "Bot đi lại mỗi Thành Thị", "widget": "number", "unit": "bot", "min": 0, "max": 3000, "step": 10,
         "desc": "Số bot ĐI LẠI trong mỗi thành thị lớn. Game chia thành 5 tốp nên số thật làm tròn xuống bội số của 5 (đặt dưới 5 = không có bot đi lại). Càng cao càng đông nhưng nặng máy."},
        {"key": "THON_SIZE", "label": "Bot đi lại mỗi Thôn/Làng", "widget": "number", "unit": "bot", "min": 0, "max": 1000, "step": 5,
         "desc": "Số bot ĐI LẠI ở thôn nhỏ, cũng làm tròn xuống bội số của 5 (đặt 1–4 = không có bot đi lại). Bot đứng bán hàng chỉnh ở ô riêng bên dưới."},
        {"key": "THANHTHI_STALL_MIN", "label": "Bot bán hàng mỗi Thành — ít nhất", "widget": "number", "unit": "bot", "min": 0, "max": 300, "step": 5,
         "desc": "Mỗi thành thị sinh ngẫu nhiên số bot ngồi bày bán hàng trong khoảng ít nhất–nhiều nhất này. Đặt cả 2 = 0 để không có ai bán hàng."},
        {"key": "THANHTHI_STALL_MAX", "label": "Bot bán hàng mỗi Thành — nhiều nhất", "widget": "number", "unit": "bot", "min": 0, "max": 300, "step": 5,
         "desc": "Phải ≥ ô 'ít nhất'. Mặc định 45–65."},
        {"key": "THON_STALL_MIN", "label": "Bot bán hàng mỗi Thôn — ít nhất", "widget": "number", "unit": "bot", "min": 0, "max": 200, "step": 1,
         "desc": "Mỗi thôn sinh ngẫu nhiên số bot ngồi bán hàng trong khoảng này. Muốn thôn vắng tanh: đặt cả 2 ô = 0."},
        {"key": "THON_STALL_MAX", "label": "Bot bán hàng mỗi Thôn — nhiều nhất", "widget": "number", "unit": "bot", "min": 0, "max": 200, "step": 1,
         "desc": "Phải ≥ ô 'ít nhất'. Mặc định 20–30."},
        {"key": "DATAU_STALL_MIN", "label": "Bot quanh Dã Tẩu — ít nhất", "widget": "number", "unit": "bot", "min": 0, "max": 200, "step": 1,
         "desc": "Số bot tụ tập quanh khu Dã Tẩu (nếu map có). Đặt cả 2 ô = 0 để tắt."},
        {"key": "DATAU_STALL_MAX", "label": "Bot quanh Dã Tẩu — nhiều nhất", "widget": "number", "unit": "bot", "min": 0, "max": 200, "step": 1,
         "desc": "Phải ≥ ô 'ít nhất'. Mặc định 20–30."},
        {"key": "TONGKIM_BOT_WAVE_MIN", "label": "Bot Tống Kim mỗi đợt — ít nhất", "widget": "number", "unit": "bot", "min": 0, "max": 500, "step": 5,
         "desc": "Mỗi đường tiến quân Tống Kim sinh ngẫu nhiên số bot trong khoảng này. Mặc định 20–40."},
        {"key": "TONGKIM_BOT_WAVE_MAX", "label": "Bot Tống Kim mỗi đợt — nhiều nhất", "widget": "number", "unit": "bot", "min": 0, "max": 500, "step": 5,
         "desc": "Phải ≥ ô 'ít nhất'. Đông quá sẽ lag chiến trường."},
        {"key": "LUYENCONG_NHOM_MIN", "label": "Bot mỗi nhóm luyện công — ít nhất", "widget": "number", "unit": "bot", "min": 1, "max": 50, "step": 1,
         "desc": "Map luyện công 9x: mỗi nhóm bot có bấy nhiêu thành viên. Mặc định 6–7."},
        {"key": "LUYENCONG_NHOM_MAX", "label": "Bot mỗi nhóm luyện công — nhiều nhất", "widget": "number", "unit": "bot", "min": 1, "max": 50, "step": 1,
         "desc": "Phải ≥ ô 'ít nhất'."},
        {"key": "THANHTHI_BANG_PCT", "label": "% bot thành thị có tên bang", "widget": "number", "unit": "%", "min": 0, "max": 100, "step": 5,
         "desc": "Tỉ lệ bot trong thành được gắn [Tên Bang] phía trước tên. Mặc định 50."},
    ]},
    {"title": "⚙️ Tự động sinh bot", "note": "Bật/tắt các nguồn tự sinh bot khi server chạy.", "fields": [
        {"key": "STARTUP_AUTOADD_THANHTHI", "label": "Tự sinh bot toàn bản đồ khi khởi động", "widget": "toggle",
         "desc": "BẬT: server vừa chạy là tự mời nhân sĩ lên tất cả bản đồ. TẮT: không tự sinh (tự gọi bằng lệnh/menu)."},
        {"key": "LUYENCONG_AUTOADD", "label": "Tự thêm bot luyện công (map 9x)", "widget": "toggle",
         "desc": "BẬT: tự thêm nhân sĩ vào các map luyện công cấp 9x cho đông."},
        {"key": "THANHTHI_QUAI", "label": "Cho quái xuất hiện trong Thành Thị", "widget": "toggle",
         "desc": "BẬT: thành thị có thêm quái tự sinh. TẮT: thành thị chỉ có nhân sĩ."},
        {"key": "THANHTHI_QUAI_1IN", "label": "Mật độ quái trong thành (1 phần N)", "widget": "number", "min": 1, "max": 20, "step": 1,
         "desc": "Khi bật quái: cứ N suất bot thì 1 suất thành quái. 3 = 1/3 là quái; 10 = thưa; 1 = toàn quái."},
    ]},
    {"title": "⚔️ Kích hoạt chiến đấu", "note": "Game liên tục 'quay số' cho từng bot (nhiều lần mỗi giây). Số càng LỚN bot càng hung hăng, 0 = tắt hẳn.", "fields": [
        {"key": "BOT_VS_BOT", "label": "Cho bot đánh nhau (khác phe)", "widget": "toggle",
         "desc": "BẬT: bot ngoài thành TỰ tìm và đánh bot khác phe, bất kể chế độ PK hay vị trí người chơi. TẮT = tắt hẳn bot đấu bot."},
        {"key": "CHANCE_AUTO_ATTACK", "label": "Tỉ lệ bot tự vào chiến đấu", "widget": "number", "unit": "/8000", "min": 0, "max": 8000, "step": 1,
         "desc": "Mỗi lần quay số, bot có (giá trị) phần 8000 cơ hội nổi máu đi tìm đối thủ. Mặc định 1 = thỉnh thoảng; tăng lên 50–100 là choảng nhau liên tục."},
        {"key": "CHANCE_JOIN_FIGHT", "label": "Tỉ lệ bot nhập trận khi đi ngang", "widget": "number", "unit": "/3000", "min": 0, "max": 3000, "step": 1,
         "desc": "Bot đi ngang chỗ đang đánh nhau có (giá trị) phần 3000 cơ hội nhảy vào tham chiến. Mặc định 1."},
        {"key": "CHANCE_ATTACK_PLAYER", "label": "Tỉ lệ bot đánh người chơi", "widget": "number", "unit": "/3000", "min": 0, "max": 3000, "step": 1,
         "desc": "Bot ở gần người chơi đang chiến đấu có (giá trị) phần 3000 cơ hội quay sang đánh người đó. Mặc định 1. Đặt 0 = bot không bao giờ đánh người."},
        {"key": "CHANCE_PREFER_PLAYER", "label": "% bot ưu tiên nhắm NGƯỜI", "widget": "number", "unit": "%", "min": 0, "max": 100, "step": 5,
         "desc": "Khi quanh bot có cả bot địch lẫn người chơi địch: bấy nhiêu % lần nó chọn NGƯỜI làm mục tiêu. Mặc định 25."},
        {"key": "SIMBOT_PROACTIVE_PLAYER", "label": "Bot chủ động lùng người chơi", "widget": "toggle",
         "desc": "BẬT: bot rảnh sẽ chủ động dò tìm người chơi để gây chiến (hung hãn hơn hẳn). Mặc định TẮT."},
    ]},
    {"title": "📡 Tầm quét / phát hiện", "note": "Bán kính (ô) bot nhìn thấy mục tiêu.", "fields": [
        {"key": "RADIUS_FIGHT_PLAYER", "label": "Tầm quét & đánh người chơi", "widget": "number", "unit": "ô", "min": 1, "max": 60, "step": 1,
         "desc": "Bán kính bot phát hiện và tấn công người chơi."},
        {"key": "RADIUS_FIGHT_NPC", "label": "Tầm quét & đánh NPC/bot", "widget": "number", "unit": "ô", "min": 1, "max": 60, "step": 1,
         "desc": "Bán kính bot phát hiện NPC/bot quanh mình để tấn công."},
        {"key": "RADIUS_FIGHT_SCAN", "label": "Tầm quét đám đánh nhau để nhập trận", "widget": "number", "unit": "ô", "min": 1, "max": 60, "step": 1,
         "desc": "Bán kính bot dò một đám đang đánh nhau gần đó để tham gia."},
        {"key": "BOT_COMBAT_RADIUS", "label": "Bán kính vùng combat của bot", "widget": "number", "unit": "ô", "min": 1, "max": 60, "step": 1,
         "desc": "Phạm vi bot hoạt động khi đã vào combat."},
        {"key": "DISTANCE_VISION", "label": "Tầm đi lạc tối đa", "widget": "number", "unit": "ô", "min": 1, "max": 60, "step": 1,
         "desc": "Bot đi lạc xa hơn khoảng này sẽ bị thu hồi và sinh lại chỗ khác (tránh bot trôi mất khỏi khu vực của nó)."},
    ]},
    {"title": "💬 Chat & rơi tiền", "fields": [
        {"key": "CHANCE_CHAT", "label": "Tỉ lệ bot chat mỗi giây", "widget": "number", "unit": "/1000", "min": 0, "max": 1000, "step": 1,
         "desc": "Mỗi giây, bot có (giá trị) phần 1000 cơ hội nói 1 câu. Mặc định 10 ≈ thỉnh thoảng; 100 = nói liên mồm; 0 = câm lặng."},
        {"key": "CHANCE_DROP_MONEY", "label": "Tỉ lệ bot rơi tiền khi di chuyển", "widget": "number", "unit": "/10000", "min": 0, "max": 10000, "step": 1,
         "desc": "Xác suất bot rơi tiền khi đi = giá trị/10000. Mặc định 0 (tắt)."},
        {"key": "DROP_MONEY_WALK_MIN", "label": "Tiền rơi khi đi — ít nhất", "widget": "number", "unit": "lượng", "min": 0, "max": 10000000, "step": 500,
         "desc": "Mỗi lần trúng tỉ lệ rơi tiền, bot rơi ngẫu nhiên trong khoảng này. Mặc định 1.000–10.000."},
        {"key": "DROP_MONEY_WALK_MAX", "label": "Tiền rơi khi đi — nhiều nhất", "widget": "number", "unit": "lượng", "min": 0, "max": 10000000, "step": 500,
         "desc": "Phải ≥ ô 'ít nhất'."},
        {"key": "DROP_MONEY_DIE_MIN", "label": "Tiền rơi khi bot chết — ít nhất", "widget": "number", "unit": "lượng", "min": 0, "max": 10000000, "step": 500,
         "desc": "Bot (ngoài chiến trường) chết có thể rơi tiền trong khoảng này. Mặc định 1.000–100.000."},
        {"key": "DROP_MONEY_DIE_MAX", "label": "Tiền rơi khi bot chết — nhiều nhất", "widget": "number", "unit": "lượng", "min": 0, "max": 10000000, "step": 500,
         "desc": "Phải ≥ ô 'ít nhất'. Cẩn thận: cao quá người chơi farm bot lấy tiền."},
    ]},
    {"title": "❤️ Hồi máu", "fields": [
        {"key": "LIFE_RESTORE_PERCENT", "label": "Bật/tắt bot tự hồi máu", "widget": "number", "unit": "%", "min": 0, "max": 100, "step": 1,
         "desc": "Đặt 0 = bot KHÔNG tự hồi máu (đánh là chết luôn). Lớn hơn 0 = có tự hồi. Còn hồi bao nhiêu máu thì chỉnh ở ô 'Lượng máu hồi mỗi 10 giây' trong nhóm Chỉ số bot."},
    ]},
    {"title": "⏱️ Thời gian đánh / nghỉ", "note": "Đơn vị mili-giây: 1000 = 1 giây. Game chọn ngẫu nhiên một khoảng giữa tối thiểu và tối đa; thời gian thật có thể nhỉnh hơn con số một chút.", "fields": [
        {"key": "TIME_FIGHTING.minTs", "label": "Thời gian đánh — tối thiểu", "widget": "number", "unit": "ms", "min": 0, "max": 60000, "step": 500,
         "desc": "Một trận đánh kéo dài ít nhất bấy nhiêu (6000 = 6 giây)."},
        {"key": "TIME_FIGHTING.maxTs", "label": "Thời gian đánh — tối đa", "widget": "number", "unit": "ms", "min": 0, "max": 60000, "step": 500,
         "desc": "Một trận đánh kéo dài nhiều nhất bấy nhiêu."},
        {"key": "TIME_RESTING.minTs", "label": "Thời gian nghỉ — tối thiểu", "widget": "number", "unit": "ms", "min": 0, "max": 60000, "step": 500,
         "desc": "Đánh xong, bot nghỉ ít nhất bấy nhiêu mới đánh tiếp."},
        {"key": "TIME_RESTING.maxTs", "label": "Thời gian nghỉ — tối đa", "widget": "number", "unit": "ms", "min": 0, "max": 60000, "step": 500,
         "desc": "Bot nghỉ lâu nhất bấy nhiêu giữa các trận."},
    ]},
    {"title": "🏯 Tống Kim", "note": "Đơn vị là nhịp xử lý của game (không phải giây) — muốn chỉnh nên tăng/giảm từng nấc nhỏ rồi xem thực tế.", "fields": [
        {"key": "SIMBOT_TK_LA_NGUOI", "label": "Bot Tống Kim là NGƯỜI (cho auto nhận PK)", "widget": "toggle",
         "desc": "BẬT: bot trong Tống Kim luôn mang loại đối tượng NGƯỜI CHƠI — VL Auto sẽ nhận diện và tự PK bot như người thật. TẮT: bot lúc đi lại bị coi là NPC nên auto bỏ qua."},
        {"key": "TONGKIM_SPAWN_MINSTAY", "label": "Ở lại đại doanh — ngắn nhất", "widget": "number", "unit": "nhịp", "min": 0, "max": 100, "step": 1,
         "desc": "Bot vừa sinh ra sẽ đứng trong đại doanh ít nhất bấy nhiêu nhịp rồi mới xông lên."},
        {"key": "TONGKIM_SPAWN_MAXSTAY", "label": "Ở lại đại doanh — lâu nhất", "widget": "number", "unit": "nhịp", "min": 0, "max": 100, "step": 1,
         "desc": "Bot nấp trong đại doanh lâu nhất bấy nhiêu nhịp là phải xông lên."},
    ]},
    {"title": "🐾 Đồng hành / bám theo người chơi", "note": "Khoảng cách (ô) điều khiển bot pet/theo sau.", "fields": [
        {"key": "DISTANCE_FOLLOW_PLAYER", "label": "Khoảng cách bắt đầu chạy theo", "widget": "number", "unit": "ô", "min": 1, "max": 60, "step": 1,
         "desc": "Nếu cách người chơi xa hơn số này, bot chạy theo."},
        {"key": "DISTANCE_SUPPORT_PLAYER", "label": "Khoảng cách chuyển sang hỗ trợ đánh", "widget": "number", "unit": "ô", "min": 1, "max": 60, "step": 1,
         "desc": "Khi ở gần người chơi trong khoảng này thì bot chuyển sang chiến đấu hỗ trợ."},
        {"key": "DISTANCE_FOLLOW_PLAYER_TOOFAR", "label": "Khoảng cách 'quá xa' → biến hình theo", "widget": "number", "unit": "ô", "min": 1, "max": 80, "step": 1,
         "desc": "Nếu quá xa (chạy nhanh), bot dịch chuyển tức thời theo người chơi."},
        {"key": "DISTANCE_CAN_CONTINUE", "label": "Ngưỡng tới đích để đi bước kế", "widget": "number", "unit": "ô", "min": 1, "max": 30, "step": 1,
         "desc": "Khi còn cách đích ≤ số này thì bắt đầu di chuyển tới điểm tiếp theo."},
        {"key": "DISTANCE_CAN_SPIN", "label": "Ngưỡng xoay hướng", "widget": "number", "unit": "ô", "min": 1, "max": 30, "step": 1,
         "desc": "Khoảng cách để bot bắt đầu xoay người chỉnh hướng đi. Ít khi cần đổi."},
        {"key": "CHAR_SPACING", "label": "Khoảng cách giữa các bot đội hình", "widget": "number", "unit": "ô", "min": 0, "max": 20, "step": 1,
         "desc": "Giãn cách giữa các nhân vật khi đi theo đội hình."},
        {"key": "SPINNING_WAIT_TIME", "label": "Thời gian chờ chỉnh vị trí", "widget": "number", "unit": "nhịp", "min": 0, "max": 100, "step": 1,
         "desc": "Bot đứng chờ bấy nhiêu nhịp để chỉnh lại chỗ đứng khi xoay hướng. Ít khi cần đổi."},
    ]},
    {"title": "💪 Chỉ số bot (nâng cao)", "note": "Đã gom từ code về config để chỉnh trên web.", "fields": [
        {"key": "SIMBOT_HP_MIN", "label": "Máu bot — tối thiểu", "widget": "number", "unit": "HP", "min": 1000, "max": 5000000, "step": 5000,
         "desc": "Sinh lực tối thiểu của bot (khi máu để chế độ auto random)."},
        {"key": "SIMBOT_HP_MAX", "label": "Máu bot — tối đa", "widget": "number", "unit": "HP", "min": 1000, "max": 5000000, "step": 5000,
         "desc": "Sinh lực tối đa của bot."},
        {"key": "SIMBOT_LEVEL", "label": "Cấp độ bot", "widget": "number", "unit": "cấp", "min": 1, "max": 156, "step": 1,
         "desc": "Cấp độ gán cho bot — hiện cạnh tên và quyết định chiêu thức trông mạnh cỡ nào. Mặc định 95."},
        {"key": "SIMBOT_ATKSPEED", "label": "Tốc độ đánh của bot", "widget": "number", "unit": "", "min": 50, "max": 1000, "step": 10,
         "desc": "Tốc độ ra đòn. SỐ NHỎ = đánh NHANH hơn. Mặc định 250."},
        {"key": "SIMBOT_WALK_SPEED", "label": "Tốc độ đi bộ của bot", "widget": "number", "unit": "", "min": 1, "max": 100, "step": 1,
         "desc": "Tốc độ lúc bot thong thả đi dạo. Mặc định 15 (ngang người chơi đi bộ). SỐ LỚN = đi nhanh hơn."},
        {"key": "SIMBOT_RUN_SPEED", "label": "Tốc độ chạy của bot", "widget": "number", "unit": "", "min": 1, "max": 100, "step": 1,
         "desc": "Tốc độ lúc bot chạy (đuổi đánh, chạy theo). Mặc định 24 ≈ người chơi chạy. Tăng lên 30–40 là bot chạy vượt mặt người."},
        {"key": "SIMBOT_HEAL_AMOUNT", "label": "Lượng máu hồi mỗi 10 giây", "widget": "number", "unit": "HP", "min": 0, "max": 500000, "step": 500,
         "desc": "Số máu bot tự hồi mỗi ~10 giây. Mặc định 3000. Đặt cao = bot rất trâu."},
        {"key": "SIMBOT_AGGRO_PLAYER_PCT", "label": "% bot 'hổ báo' với người chơi", "widget": "number", "unit": "%", "min": 0, "max": 100, "step": 1,
         "desc": "Trong 100 bot thì khoảng bấy nhiêu con thuộc loại thấy người chơi là chủ động gây sự trước. Mặc định 30."},
        {"key": "SIMBOT_ATTACK_PLAYER_CHANCE", "label": "Độ hung dữ khi bốc thăm đánh người", "widget": "number", "unit": "", "min": 0, "max": 20, "step": 1,
         "desc": "Bot 'bốc thăm' để quyết định có đánh người chơi không. Số càng NHỎ bot càng DỄ ra tay. Mặc định 3."},
        {"key": "SIMBOT_CITY_BUFF_PCT", "label": "% bot có buff hỗ trợ", "widget": "number", "unit": "%", "min": 0, "max": 100, "step": 5,
         "desc": "Tỉ lệ bot được bật hiệu ứng buff (nhìn 'chất' hơn, mạnh hơn chút). Mặc định 30."},
        {"key": "SIMBOT_KEEP_WALKING_PCT", "label": "% bot đi tiếp không dừng nghỉ", "widget": "number", "unit": "%", "min": 0, "max": 100, "step": 5,
         "desc": "Tới điểm dừng, bấy nhiêu % lần bot đi tiếp luôn thay vì đứng nghỉ. Mặc định 90. Thấp = phố xá 'chậm rãi' hơn."},
        {"key": "SIMBOT_HP_CAP1_MIN", "label": "Máu bot thường (cấp 1) — ít nhất", "widget": "number", "unit": "HP", "min": 100, "max": 5000000, "step": 1000,
         "desc": "Bot dân thành thị thuộc cấp máu 1. Mặc định 10.000–20.000."},
        {"key": "SIMBOT_HP_CAP1_MAX", "label": "Máu bot thường (cấp 1) — nhiều nhất", "widget": "number", "unit": "HP", "min": 100, "max": 5000000, "step": 1000,
         "desc": "Phải ≥ ô 'ít nhất'."},
        {"key": "SIMBOT_HP_CAP2_MIN", "label": "Máu bot khá (cấp 2) — ít nhất", "widget": "number", "unit": "HP", "min": 100, "max": 5000000, "step": 1000,
         "desc": "Cấp máu trung. Mặc định 30.000–40.000."},
        {"key": "SIMBOT_HP_CAP2_MAX", "label": "Máu bot khá (cấp 2) — nhiều nhất", "widget": "number", "unit": "HP", "min": 100, "max": 5000000, "step": 1000,
         "desc": "Phải ≥ ô 'ít nhất'."},
        {"key": "SIMBOT_HP_CAP3_MIN", "label": "Máu bot trâu (cấp 3) — ít nhất", "widget": "number", "unit": "HP", "min": 100, "max": 5000000, "step": 1000,
         "desc": "Cấp máu cao nhất. Mặc định 50.000–80.000."},
        {"key": "SIMBOT_HP_CAP3_MAX", "label": "Máu bot trâu (cấp 3) — nhiều nhất", "widget": "number", "unit": "HP", "min": 100, "max": 5000000, "step": 1000,
         "desc": "Phải ≥ ô 'ít nhất'."},
    ]},
    {"title": "💐 Tiểu Thiếp (xin tiền / thuốc / TDP)", "note": "Người chơi bấm chuyện trò với Tiểu Thiếp có thể xin tiền, xin thuốc, xin TDP — chỉnh độ hào phóng ở đây.", "fields": [
        {"key": "TIEUTHIEP_CHO_TIEN_PCT", "label": "% đồng ý cho tiền", "widget": "number", "unit": "%", "min": 0, "max": 100, "step": 5,
         "desc": "Xin tiền thì bấy nhiêu % lần nàng chịu rút hầu bao (còn lại từ chối khéo). Mặc định 10. Đặt 0 = không bao giờ cho."},
        {"key": "TIEUTHIEP_TIEN_MIN", "label": "Tiền cho — ít nhất", "widget": "number", "unit": "vạn", "min": 0, "max": 10000, "step": 1,
         "desc": "Khi chịu cho, số tiền ngẫu nhiên trong khoảng ít nhất–nhiều nhất (đơn vị VẠN lượng). Mặc định 1–5 vạn."},
        {"key": "TIEUTHIEP_TIEN_MAX", "label": "Tiền cho — nhiều nhất", "widget": "number", "unit": "vạn", "min": 0, "max": 10000, "step": 1,
         "desc": "Phải ≥ ô 'ít nhất'. Cẩn thận đặt cao: người chơi có thể đứng xin cả ngày."},
        {"key": "TIEUTHIEP_SO_THUOC", "label": "Số thuốc cho mỗi lần xin", "widget": "number", "unit": "viên", "min": 0, "max": 500, "step": 5,
         "desc": "Xin thuốc là rơi ra bấy nhiêu viên. Mặc định 25. Đặt 0 = tắt."},
        {"key": "TIEUTHIEP_SO_TDP", "label": "Số TDP cho mỗi lần xin", "widget": "number", "unit": "cái", "min": 0, "max": 100, "step": 1,
         "desc": "Xin TDP là rơi ra bấy nhiêu cái. Mặc định 3. Đặt 0 = tắt."},
    ]},
    {"title": "🔧 Hệ thống (chỉnh cẩn thận)", "note": "Ảnh hưởng hiệu năng/định danh nội bộ — không nên đổi nếu chưa hiểu.", "fields": [
        {"key": "REFRESH_RATE", "label": "Nhịp suy nghĩ của bot", "widget": "number", "unit": "", "min": 1, "max": 200, "step": 1,
         "desc": "Bao lâu bot 'suy nghĩ' một lần. Số NHỎ = bot phản ứng nhanh, mượt hơn nhưng máy chủ nặng hơn. Mặc định 18."},
        {"key": "ENABLE_BANNGUAMIXDEV", "label": "Bật khi dùng bản mix dev (chống mất bắn ngựa)", "widget": "toggle",
         "desc": "Đặt 1 nếu xài bản mix dev vì bị mất bắn ngựa. Bình thường để 0."},
        {"key": "PARAM_LIST_ID", "label": "[nội bộ] Ô nhớ nhận diện bot", "widget": "number", "min": 0, "max": 20, "step": 1,
         "desc": "Ô nhớ engine dùng để nhận diện bot. Đổi sai là bot loạn hết. KHÔNG nên đổi."},
        {"key": "PARAM_CHILD_ID", "label": "[nội bộ] Ô nhớ nhận diện bot con", "widget": "number", "min": 0, "max": 20, "step": 1,
         "desc": "Ô nhớ engine dùng để nhận diện bot con trong nhóm. KHÔNG nên đổi."},
        {"key": "PARAM_TYPE", "label": "[nội bộ] Ô nhớ phân loại bot", "widget": "number", "min": 0, "max": 20, "step": 1,
         "desc": "Ô nhớ engine dùng để phân loại bot. KHÔNG nên đổi."},
    ]},
]

# ---- Hằng số ở FILE KHÁC (được scan & gắn nhãn) ----
OTHER_FILE_LABELS = {
    "SIMBOT_RANGED_DIST": {"label": "Tầm đánh xa", "widget": "number", "unit": "ô", "min": 1, "max": 40,
                           "desc": "Đối thủ trong khoảng này thì bot bắn chiêu từ xa. (sim.core.lua)"},
    "SIMBOT_MELEE_DIST": {"label": "Tầm đánh gần", "widget": "number", "unit": "ô", "min": 1, "max": 20,
                          "desc": "Bot áp sát tới khoảng này mới vung đòn cận chiến. (sim.core.lua)"},
    "SIMBOT_NGAMI_BUFF": {"label": "Nga Mi tự buff", "widget": "toggle",
                          "desc": "BẬT: bot phái Nga Mi tự dùng chiêu hồi máu/tăng lực cho mình và đồng đội. (sim.fight.lua)"},
    "SIMBOT_TRANPHAI": {"label": "Bot ra chiêu theo môn phái", "widget": "toggle",
                        "desc": "BẬT: bot dùng chiêu thức đúng môn phái của nó (Thiếu Lâm đánh quyền, Đường Môn phóng ám khí...). (sim.fight.lua)"},
    "SIMBOT_AGGRO_PLAYER": {"label": "Bot chủ động gây sự với người chơi", "widget": "toggle",
                            "desc": "BẬT: bot dám đánh người chơi trước kể cả khi chưa bị đánh. TẮT: bot chỉ phản đòn. (group_fighter.class.lua)"},
    "SIMCITY_CITY_RADIUS": {"label": "Bán kính vùng thành thị", "widget": "number", "unit": "ô", "min": 10, "max": 200,
                            "desc": "Phạm vi được tính là 'trong thành' để rải bot và giới hạn bot đi lại. (common.lua)"},
    "g_TK_BangChance": {"label": "% bot có tên bang hội", "widget": "number", "unit": "%", "min": 0, "max": 100,
                        "desc": "Tỉ lệ bot được gắn tên bang hội [Tên Bang] phía trước. 0 = không bot nào có tên bang. (sim_citizen.lua)"},
    # --- Nội bộ hệ thống: hiện nhãn để người dùng biết mà TRÁNH đụng vào ---
    "settingsPath": {"label": "[nội bộ] Thư mục dữ liệu bot", "widget": "text",
                     "desc": "Nơi game đọc dữ liệu tên bot, câu chat, thú cưng (names.txt, chat.txt, pets.txt). KHÔNG nên đổi. (libs/data.lua)"},
    "VATNUOI_TSK_PET_IDS": {"label": "[nội bộ] Ô nhớ lưu thú cưng đã mua", "widget": "number",
                            "desc": "Số hiệu ô nhớ engine dùng lưu thú cưng của người chơi. Đổi là MẤT dữ liệu pet đã mua. KHÔNG nên đổi. (plugins/pvatnuoi.lua)"},
    "VATNUOI_TSK_PET_FACTIONS": {"label": "[nội bộ] Ô nhớ lưu môn phái thú cưng", "widget": "number",
                                 "desc": "Như trên — ô nhớ engine của hệ thống thú cưng. KHÔNG nên đổi. (plugins/pvatnuoi.lua)"},
    "VATNUOI_TSK_PET_SKILLS_1": {"label": "[nội bộ] Ô nhớ kỹ năng thú cưng #1", "widget": "number",
                                 "desc": "Như trên — ô nhớ engine của hệ thống thú cưng. KHÔNG nên đổi. (plugins/pvatnuoi.lua)"},
    "VATNUOI_TSK_PET_SKILLS_2": {"label": "[nội bộ] Ô nhớ kỹ năng thú cưng #2", "widget": "number",
                                 "desc": "Như trên — ô nhớ engine của hệ thống thú cưng. KHÔNG nên đổi. (plugins/pvatnuoi.lua)"},
    "VATNUOI_TSK_PET_SKILLS_3": {"label": "[nội bộ] Ô nhớ kỹ năng thú cưng #3", "widget": "number",
                                 "desc": "Như trên — ô nhớ engine của hệ thống thú cưng. KHÔNG nên đổi. (plugins/pvatnuoi.lua)"},
}

# LOOKUP: key/tên -> meta (gộp config.lua + file khác)
LOOKUP = {}
for _g in GROUPS:
    for _f in _g["fields"]:
        LOOKUP[_f["key"]] = _f
for _k, _m in OTHER_FILE_LABELS.items():
    LOOKUP.setdefault(_k, {**_m, "key": _k})
